# LGA housing targets (Template)

```{rtodo }

# knitr::opts_chunk$set(message = FALSE, warning = FALSE, error = FALSE, echo = FALSE, dpi = 300,fig.width = 7, fig.height = 4)
# knitr::opts_knit$set(root.dir= '../')   

parcels <- prettyNum(nrow(df_lga_props),big.mark = ",")

fois <- df_lga_props %>% 
  filter(feature_preventing_development) %>% 
  nrow()%>% 
  prettyNum(big.mark = ",")
  
bad_zoning <- df_lga_props %>% 
    filter(!feature_preventing_development) %>% 
  group_by(zoning_permits_housing) %>% 
  summarise(n=n()) %>% 
  filter(zoning_permits_housing == "Housing not generally permitted") %>% 
  pull(n) %>% 
  prettyNum(big.mark = ",")

already_developed <- df_lga_props %>% 
  filter(zoning_permits_housing == "Housing permitted",
         !feature_preventing_development,
         dwellings_est>1) %>%
  nrow()%>% 
  prettyNum(big.mark = ",")


df_lga_useful_props_num <-  prettyNum(nrow(df_lga_useful_props),big.mark = ",")

mcg_size <- 20000 

# Corrected function to generate a button with customizable text and link
generateButton <- function(text, link) {
  buttonHTML <- paste0('<div class="button-row"><div style="opacity: 1; transform: translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg); transform-style: preserve-3d;" class="button-wrapper"><a href="', link, '" class="button-fullwidth-2 w-inline-block"><div style="width: 0%; height: 2px;" class="bottom-line-2"></div><div style="height: 0%; width: 2px;" class="left-line-2"></div><div style="width: 0%; height: 2px;" class="top-line-2"></div><div style="height: 0%; width: 2px;" class="right-line-2"></div><div style="height: 0%; width: 538.617px;" class="overlay-colr-button-2"></div><div style="color: rgb(0, 0, 0);" class="button-text">', text, '</div></a></div></div>')
  cat(buttonHTML)
}


```

```{rtodo }


mm_number <- df_lga_useful_props %>% filter(zone_short_mm == "Missing middle") %>% nrow() %>% prettyNum(big.mark = ",")
rgz_number <- df_lga_useful_props %>% filter(zone_short_mm == "Residential growth") %>% nrow() %>% prettyNum(big.mark = ",")
grz_number <- df_lga_useful_props %>% filter(zone_short_mm == "General residential") %>% nrow() %>% prettyNum(big.mark = ",")


```

In `rtodo area_name`, `rtodo mm_number` lots would be upzoned to the Missing Middle Zone (MMZ), enabling six-storey medium-density near all transit. A further `rtodo rgz_number` properties will be rezoned from General Residential Zone (GRZ) to Residential Growth (RGZ), and `rtodo grz_number` from Neighbourhood Residential Zone (NRZ) to GRZ. 

Broad upzoning is needed across existing suburbs so that there is more land available to build homes for our children to live in. If only a few select areas are rezoned, then developers will be able to buy up that land and withhold supply. Broad upzoning of land across inner-Melbourne removes any power developers may have to speculate, and lowers housing costs for all.

## Upzoning `rtodo area_name`  {.tabset}

The answer to the housing supply shortage will not be found in this handful of designated activity centres and precincts. `rtodo area_name` needs to do its bit by delivering beautiful mid-rise homes near every one of its train and tram stops. 

Through broad transit-oriented upzoning and development, `rtodo area_name` can deliver housing abundance and provide more housing choices to all current and future residents across the entirety of the city. This will fulfil the original goal of Plan Melbourne creating a vast array of 20-minute neighbourhoods, rather than a small number of scattered activity centres.

```{rtodo }


mm_number <- df_lga_useful_props %>% filter(zone_short_mm == "Missing middle") %>% nrow() %>% prettyNum(big.mark = ",")
rgz_number <- df_lga_useful_props %>% filter(zone_short_mm == "Residential growth") %>% nrow() %>% prettyNum(big.mark = ",")
grz_number <- df_lga_useful_props %>% filter(zone_short_mm == "General residential") %>% nrow() %>% prettyNum(big.mark = ",")


```

In `rtodo area_name` missing middle upzoning will have the following effect:

* `rtodo mm_number` lots would be upzoned to the Missing Middle Zone (MMZ), enabling 6 storeys near all tram stops and train stations

*  `rtodo rgz_number` properties will be rezoned from General Residential Zone (GRZ) to Residential Growth (RGZ), enabling 4 storeys where 3 is currently permitted

*  `rtodo grz_number` from Neighbourhood Residential Zone (NRZ) to GRZ, enabling 3 storeys where 2 is currently permitted

Broad upzoning is needed across existing suburbs so that there is more land available to build homes for our children to live in. If only a few select areas are rezoned, then developers will be able to buy up that land and withhold supply. Broad upzoning of land across inner-Melbourne removes any power developers may have to speculate, and lowers housing costs for all.


### New zoning

```{rtodo}make_map(sf_lga_props,"category_new")
```


### Existing zoning

```{rtodo}make_map(sf_lga_props,"category")
```

## More zoned capacity for homes in `rtodo params$area`

```{rtodo}
zoned_capacity_x <- lga_summary %>% 
  mutate( change_to_zoned_capacity = paste0(round(change_to_zoned_capacity,1),"x")) %>% 
  pull(change_to_zoned_capacity)
```

There are `rtodo parcels` parcels of land in `rtodo params$area`. But not every piece of land can have housing on it. Of these parcels: 

* `rtodo fois` are on civic land like schools, hospitals, or train stations where development is challenging. 

* Another `rtodo bad_zoning` are in zones that do not allow housing to be built. 

* Finally `rtodo already_developed` lots have already been developed with more than 1 unit, making re-development difficult. 

That leaves `rtodo df_lga_useful_props_num` parcels that are available for development. The size of these lots is `rtodo prettyNum(sum(df_lga_useful_props$lot_size),big.mark = ",")` square meters, or `rtodo round(as.numeric(sum(df_lga_useful_props$lot_size))/mcg_size)` MCGs worth of space to build dense housing. 

Under existing zoning, `rtodo area_name` has an estimated zoned capacity of `rtodo prettyNum(round(lga_summary$zoned_capacity,-3), big.mark = ",")`. 

YIMBY Melbourne's plan for `rtodo area_name` increases its zoned capacity by `rtodo zoned_capacity_x`, to `rtodo prettyNum(round(lga_summary$mm_zoned_capacity,-3), big.mark = ",")` — enabling many more opportunities for dense housing to be built across the entire city.


## Housing targets for `rtodo params$area` 

Even though there are `rtodo prettyNum(round(lga_summary$mm_zoned_capacity,-3), big.mark = ",")` possible units that could be built in `rtodo area_name`, it's impossible for them to be built all at once. It is also not reasonable to assume that all possible units will ever be built, which is [The importance of excess zoned capacity]. 

For each lot in `rtodo area_name`, we calculated whether it would be profitable to build housing under upzoning. We estimate that a potential __`rtodo prettyNum(round(lga_summary$profitable_apartments,-3), big.mark = ",")` units__ could be built profitably in `rtodo area_name`. 

To contribute its fair share to the the statewide target of 80,000 new homes per year, `rtodo area_name` must build  **`rtodo prettyNum(round(lga_summary$mm_target,-3), big.mark = ",")` units** per year.^1^ 

*^1^ This figure is in addition to homes that would be built as part of any rezoning process such as through Fishermans' Bend or the Suburban Rail Loop precincts.*


## `rtodo area_name` is falling behind due to restrictive zoning {.tabset}

`rtodo area_name` needs the missing middle rezoning, because under current zoning the LGA is not keeping up with population growth. 

While there has been some housing construction, many homes have more bedrooms free than ever before as children move out of home. As such, the total number of homes is struggling to keep up with Melbourne's evolving housing needs. 

```{rtodo}

#source("R/import_lga_pop_data.R")

mel_total <- lga_pop_change_importer(area_name, type = "population")


lga_change <- mel_total %>% 
  filter(year == 2021,
         lga_name_2021 == area_name) %>%
  pull(change)

mel_change <- mel_total %>% 
  filter(year == 2021,
         lga_name_2021 == "All of Melbourne") %>%
  pull(change)


  
change_ratio <- lga_change/mel_change

## TODO - get PT stops per LGA. 

text_on_growth <- case_when(change_ratio >.9 ~ paste0(params$area, " has been building housing, but cannot rest on its laurels."),
                            change_ratio >.7 ~ paste0(params$area, " has been building some housing, but it is still barely keeping up with the average for Melbourne."),
                            T ~ paste0(params$area, " is falling well behind the average for new housing in Melbourne.")
)

```

`rtodo text_on_growth` The area has good public transport running through it, and it needs to do more to ensure that housing is abundant around this infrastructure. 

```{rtodo}
mel_total %>%
  ggplot(aes( x= year, y = change,
              colour = lga_name_2021))+
  geom_line(stat = "identity",linewidth = 1)+
  theme_yimby_mel_caption(caption = "source: ABS. ",
                          text_size = "small",
                          plot_type = "line",
                          colour_scale = "c")+
  labs(title = paste("Growth in homes for",area_name,"compared to the rest of Melbourne"),
       subtitle = "Growth in census dwellings since 2006",
       labs = element_blank(),
       colour = "Area",
       x = element_blank(),
       y = element_blank())+
  scale_y_continuous(labels = scales::percent_format())


```

The reason `rtodo area_name` is not building enough housing is because there are not enough areas where housing can be built. The graph below shows that the majority of land in `rtodo area_name` is locked away, preventing "Missing Middle" density from being unlocked.

### By number of lots

```{rtodo}

dwellings_by_type <- df_lga_useful_props %>%
  group_by(category) %>% 
  summarise(n = n(),
            lot_size = sum(lot_size),
            .groups = "drop") %>% 
  group_by(category) %>% 
  mutate(n_total = sum(n),
         lot_size_total = sum(lot_size))  %>% 
  ungroup() 

dwellings_by_type %>% 
  mutate(category = fct_reorder(category,n_total)) %>% 
  ggplot(aes(x = category, 
             y = n))+
  coord_flip()+ 
  geom_bar(stat = "identity")+
  theme_yimby_mel_caption(text_size = "small",plot_type = "bar",colour_scale = "light_dark") +
  labs(x = element_blank(),
       title = paste0("Land in ",area_name," by type"),
       y = "Number of properties",
       fill = "Heritage status")

```

### By total area

```{rtodo by total area 03}
dwellings_by_type %>% 
    mutate(category = fct_reorder(category,lot_size_total)) %>%
  ggplot(aes(x = category, 
             y = lot_size_total))+
  coord_flip()+ 
  geom_bar(stat = "identity")+
  theme_yimby_mel_caption(text_size = "small",plot_type = "bar",colour_scale = "light_dark") +
  labs(x = element_blank(),
       title = paste0("Land in ",area_name," by type"),
       y = "Area (sqm)",
       fill = "Heritage status")+
  scale_y_continuous(labels = scales::number_format(big.mark = ","))

```

### Table
```{rtodo}
library(kableExtra)
library(gt)

dwellings_by_type_w_heritage <- df_lga_useful_props %>%
  group_by(category,heritage) %>% 
  summarise(n = n(),
            lot_size = sum(lot_size),
            .groups = "drop") %>% 
  group_by(category) %>% 
  mutate(n_total = sum(n),
         lot_size_total = sum(lot_size))  %>% 
  ungroup() %>% 
  mutate(heritage = if_else(heritage,
                            "Subject to heritage controls",
                            "Free from heritage"))

types_zonning <- df_lga_useful_props %>% 
  group_by(heritage) %>% 
  summarise(n = n(),
            lot_size = sum(lot_size)) %>% 
  mutate(category = "Total")%>% 
  mutate(heritage = if_else(heritage,
                            "Subject to heritage controls",
                            "Free from heritage"))


types_total_new <- df_lga_useful_props %>%
  filter(!feature_preventing_development,
         zoning_permits_housing == "Housing permitted",
         dwellings_est < 2) %>% 
  group_by(heritage) %>% 
  summarise(n = n(),
            lot_size = sum(lot_size),
            .groups = "drop") %>% 
  mutate(heritage = if_else(heritage,
                            "Subject to heritage controls",
                            "Free from heritage"),
         category = "Total where new housing can be built") 

dwellings_by_type_w_heritage %>% 
  bind_rows(types_zonning) %>% 
  bind_rows(types_total_new) %>% 
  group_by(category) %>% 
  mutate(`Share of properties that are heritage` = paste0(round(100*n/sum(n)),"%"),
         `Share of land that is heritage` =  paste0(round(100*lot_size/sum(lot_size)),"%")
         ) %>% 
  rename(`Number of properties` = n,
         `Area (sqm)` = lot_size,
         ` ` = heritage) %>% 
  select(-n_total,-lot_size_total) %>% 
    gt()  %>% 
  fmt_number(decimals = 0)
```

## Existing development controls 

```{rtodo}```

Of the `rtodo prettyNum(round(lga_summary$profitable_apartments,-4), big.mark = ",")` potentially profitable apartments that could be built in `rtodo area_name`, `rtodo heritage_no` of these potential future homes are on lots subject to heritage controls. 

If heritage and neighbourhood character protections in `rtodo area_name` are too far-reaching, it could potentially affect `rtodo area_name`'s ability to meet its housing targets. 

We have outlined potential remedies for this [earlier in the report](#report-link).

[Return to LGA list](#report-link)

**An image here should end the article.**